// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpBox: typeof import('~icons/ep/box')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    Item: typeof import('./components/SidebarContainer/src/Item.vue')['default']
    Link: typeof import('./components/SidebarContainer/src/Link.vue')['default']
    Logo: typeof import('./components/SidebarContainer/src/Logo.vue')['default']
    MenuContainer: typeof import('./components/MenuContainer/index.vue')['default']
    MenuList: typeof import('./components/SidebarContainer/src/SidebarList.vue')['default']
    MenuTemplate: typeof import('./components/SidebarContainer/src/MenuTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarContainer: typeof import('./components/SidebarContainer/index.vue')['default']
    SidebarItem: typeof import('./components/SidebarContainer/src/SidebarItem.vue')['default']
    SidebarList: typeof import('./components/SidebarContainer/src/SidebarList.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }
}
